Only declare virtual/bootloader fix on arm
boot-partition image currently fails to build on non-uboot machines:
```
ERROR: Nothing PROVIDES 'virtual/bootloader'
u-boot PROVIDES virtual/bootloader but was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
u-boot-sunxi PROVIDES virtual/bootloader but was skipped: incompatible with machine qemux86 (not in COMPATIBLE_MACHINE)
u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the qemux86 machine configuration.
ERROR: Required build target 'boot-partition' has no buildable providers.
Missing or unbuildable dependency chain was: ['boot-partition', 'virtual/bootloader']
```